#服务器名是在velocity配置文件中的名字。
#离线玩家需要进入的认证服务器名
offlineServer: main

# 在线玩家不做处理默认进入velocity中的默认服务器

# 需要禁用的命令列表
disabledCommands:
  - server
  - find

#禁用命令需要作用的服务器列表
disabledCommandsServers:
  - main
  - lobby

#未完成的功能
#对于在线玩家是否使用离线UUID
useOfflineUUID: true

#关闭本地验证
disableLocalAuth: false

#本机验证缓存时间
localAuthCacheTime: 300